### PR TITLE
fix the whitespace indent problem

### LINKED ISSUE #9: difficulties with no-trailing-spaces rule
There was a new rule added, [no-trailing-spaces](https://github.com/rwjblue/ember-template-lint/blob/master/docs/rule/no-trailing-spaces.md), that doesn't play well with indented templates:

```js
test('it renders', function(assert) {
  this.render(hbs`
    {{member-component
      template block text
    }}
  `); // <-- "trailing spaces"
});
```

To be compatible with the rule, all templates would have to have ugly indentation:

```js
test('it renders', function(assert) {
  this.render(hbs`
    {{member-component
      template block text
    }}
`);
});
```

Instead of altering all the tests, would you be open to trimming or un-indenting the template before you send it to the linter?

cc @rwjblue

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #9.

Let me know if you want me to pursue this further.

cc @rwjblue

### CODE REVIEW

**Comment by kellyselden** [comment]
Definitely, I just didn't know if this PR was going to get any attention so didn't put any work into it.

**Comment by jamesarosen** [comment]
Understood. Definitely valuable to support all standard options!

**Comment by kellyselden** [comment]
I extracted the function, but I don't know how to do any additional testing. Your tests just that the parser doesn't crash, you don't have a system that I see to test actual template rules.

**Comment by psbanka** [comment]
Thanks, @kellyselden – nice work. I'll spend some time getting more tests written 😃

**Pull request merged**
